parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8

        # With Symfony 3.3, remove the `resolve:` prefix
        url: '%env(resolve:DATABASE_URL)%'
        types:
            person_id:  App\Infrastructure\Persistence\Doctrine\Type\PersonIdType
            household_id:  App\Infrastructure\Persistence\Doctrine\Type\HouseholdIdType
            pet_id:  App\Infrastructure\Persistence\Doctrine\Type\PetIdType
            pet_type:  App\Infrastructure\Persistence\Doctrine\Type\PetTypeType
            gender:  App\Infrastructure\Persistence\Doctrine\Type\GenderType
            invitation_id:  App\Infrastructure\Persistence\Doctrine\Type\InvitationIdType
            occupant_id:  App\Infrastructure\Persistence\Doctrine\Type\OccupantIdType
            task_id:  App\Infrastructure\Persistence\Doctrine\Type\TaskIdType
            task_completion_id:  App\Infrastructure\Persistence\Doctrine\Type\TaskCompletionIdType
            recurrence_rule:  App\Infrastructure\Persistence\Doctrine\Type\RecurrenceRuleType

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            datetime_functions:
                date: App\Infrastructure\Persistence\Doctrine\Functions\Date
        mappings:
            App:
                is_bundle: false
                mapping: true
                type: yml
                dir: "%kernel.root_dir%/Infrastructure/Persistence/Doctrine/config"
                prefix: App\Domain
                alias: App