language: php

php:
  - 7.1

services:
  - docker

branches:
  only:
  - master
  - develop

before_install:
  - sudo /etc/init.d/mysql stop
  - make jwt-setup
  - make up

install:
  - docker exec -it pet-feeder-php make install

script:
  - docker exec -it pet-feeder-php make cs
  - docker exec -it pet-feeder-php make test-cov
  - sonar-scanner

addons:
  sonarcloud:
    organization: "rafalkot-github"