# Read the documentation: https://github.com/hautelook/AliceBundle/blob/v1.4.1/README.md
hautelook_alice:
    fixtures_path: 'tests/DataFixtures/ORM'
    root_dirs:
        - '%kernel.root_dir%'
        - '%kernel.project_dir%'
