auth_login:
    path: /api/auth/login

auth_validate_token:
  path: /api/auth/validateToken
  controller: App\Ui\Rest\Controller\AuthController::validateTokenAction
  prefix:  /api
  methods: [GET]

register:
    path: /api/persons
    controller: App\Ui\Rest\Controller\PersonsController::postAction
    methods: [POST]

pets:
    type:     rest
    resource: App\Ui\Rest\Controller\PetsController
    prefix:  /api

tasks:
    type:     rest
    resource: App\Ui\Rest\Controller\TasksController
    prefix:  /api

scheduled_tasks:
    type:     rest
    resource: App\Ui\Rest\Controller\ScheduledtasksController
    prefix:  /api
